import type { Metadata } from "next"
import { Inter } from "next/font/google"
import { Header } from "../components/header"
import { Footer } from "../components/footer"
import "./globals.css"

const inter = Inter({ subsets: ["latin"] })

export const metadata: Metadata = {
    title: "Linear - A better way to build products",
    description: "Generated by create next app",
}

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode
}>) {
    return (
        <html lang="en">
            <body className={inter.className}>
                <Header />
                <main className="glow-gradient pt-[--nav-height]">
                    {children}
                </main>
                <Footer />
            </body>
        </html>
    )
}
